[server]

[security]

[users]

[auth.anonymous]
enabled = true
org_role = Viewer

[panels]
disable_sanitize_html = true

[frontend]
# Inject custom CSS to remove log level background colors
custom_styles = /etc/grafana/custom.css
